### PR TITLE
KB-029

### PR DESCRIPTION
**Pull request by giovannipaul**
Recompiled libvideo with my own change, now it should work

### CODE REVIEW

**Comment by giovannipaul** [comment]
[KB-029 Bug: Some YouTube videos can't be downloaded URI error](https://trello.com/c/XTjV6spX/29-kb-029-bug-some-youtube-videos-cant-be-downloaded-uri-error)

**Comment by natansystem** [comment]
Excuse my ignorance, if you could help me?
which is the most updated holder for libvideo I do not work the URI

**Comment by giovannipaul** [comment]
Hey Natan! I used a pull request someone made for libvideo. You can find the compiled version under the BusinessLayer project of my solution.

Just make a reference to it in your own project. Let’s hope the owner of libvideo repo will merge this PR soon!

**Comment by giovannipaul** [comment]
https://github.com/i3arnon/libvideo/pull/61

**Pull request merged**
